#DataSource Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/spring_rest?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
server:
  servlet:
    contextPath: /api
logging:
  level:
    org:
      apache: DEBUG
